import "@/src/globals.css";
import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
config.autoAddCss = false
import type { Metadata } from "next";
import { BsGithub, BsTwitter } from "react-icons/bs";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
      

    <div className="flex-shrink-0 text-white "> 
        <div className="border-b bg-slate-100">
      <nav className="container flex justify-between items-center">
        <div className="font-semibold">
        <svg
            className="fill-current h-8 w-8 mr-2 text-red"
            width="54"
            height="54"
            viewBox="0 0 54 54"
            xmlns="http://www.w3.org/2000/svg"
          >
            <path d="M13.5 22.1c1.8-7.2 6.3-10.8 13.5-10.8 10.8 0 12.15 8.1 17.55 9.45 3.6.9 6.75-.45 9.45-4.05-1.8 7.2-6.3 10.8-13.5 10.8-10.8 0-12.15-8.1-17.55-9.45-3.6-.9-6.75.45-9.45 4.05zM0 38.3c1.8-7.2 6.3-10.8 13.5-10.8 10.8 0 12.15 8.1 17.55 9.45 3.6.9 6.75-.45 9.45-4.05-1.8 7.2-6.3 10.8-13.5 10.8-10.8 0-12.15-8.1-17.55-9.45-3.6-.9-6.75.45-9.45 4.05z" />
          </svg>
          <span className="font-semibold text-xl tracking-tight">
            IsolaKwaMUNTU
          </span>
        </div>
        <div className="flex items-center gap-4 text-lg">
          <a href="https://github.com/Yazdun/react-fcc-forms" target="_blank">
            <BsGithub />
          </a>
          <a href="https://twitter.com/Yazdun" target="_blank">
            <BsTwitter />
          </a>
        </div>
      </nav>
      </div>
      </div>
        <div className="w-60% p-12 flex items-center justify-center bg-black text-white">

        {children}

      </div>
      </body>
    </html>
  );
}
